#!/bin/sh
# Run from OPENFOAM applications/ directory only
cd "${0%/*}" || exit
wmake -check-dir "$WM_PROJECT_DIR/applications" 2>/dev/null || {
    echo "Error (${0##*/}) : not located in \$WM_PROJECT_DIR/applications"
    echo "    Check your OpenFOAM environment and installation"
    exit 1
}
if [ -f "$WM_PROJECT_DIR"/wmake/scripts/AllwmakeParseArguments ]
then  . "$WM_PROJECT_DIR"/wmake/scripts/AllwmakeParseArguments || \
    echo "Argument parse error"
else
    echo "Error (${0##*/}) : WM_PROJECT_DIR appears to be incorrect"
    echo "    Check your OpenFOAM environment and installation"
    exit 1
fi

echo ========================================
echo Compile OpenFOAM applications
echo ========================================

#------------------------------------------------------------------------------

#wmake -all $targetType utilities
#wmake -all $targetType solvers

# Compile a few solvers
wmake $targetType $FOAM_SOLVERS/incompressible/simpleFoam
wmake $targetType $FOAM_SOLVERS/incompressible/pimpleFoam
wmake $targetType $FOAM_SOLVERS/compressible/rhoSimpleFoam

# Compile a few utils
wmake $targetType $FOAM_UTILITIES/parallelProcessing/decomposePar
wmake $targetType $FOAM_UTILITIES/parallelProcessing/reconstructPar
wmake $targetType $FOAM_UTILITIES/mesh/generation/blockMesh
wmake $targetType $FOAM_UTILITIES/mesh/manipulation/checkMesh


# Extra tools (optional)
## wmake -all $targetType tools

#------------------------------------------------------------------------------

echo ========================================
echo Done OpenFOAM applications
echo ========================================

#------------------------------------------------------------------------------
