name: docker

on:
  push:
    branches:
      - v2506-ad

jobs:
  push_to_registry:
    name: deploy
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Build and push
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u dafoam --password-stdin
        docker pull dafoam/openfoam:2506
        docker run -i -d -u dockeruser --name build_latest dafoam/openfoam:2506 /bin/bash
        docker exec -i build_latest /bin/bash -c "cd /home/dockeruser/OpenFOAM && rm -rf OpenFOAM-AD && wget https://github.com/DAFoam/OpenFOAM-AD/archive/refs/heads/v2506-ad.tar.gz && tar -xf v2506-ad.tar.gz && mv OpenFOAM-AD* OpenFOAM-AD"
        docker exec -i build_latest /bin/bash -c "cd /home/dockeruser/OpenFOAM/OpenFOAM-AD && sed -i 's/export WM_AD_MODE=.*/export WM_AD_MODE=ADF/' etc/bashrc && . etc/bashrc && export WM_QUIET=true && ./Allwmake -j && rm -rf build"
        docker exec -i build_latest /bin/bash -c "cd /home/dockeruser/OpenFOAM/OpenFOAM-AD && sed -i 's/export WM_AD_MODE=.*/export WM_AD_MODE=ADR/' etc/bashrc && . etc/bashrc && export WM_QUIET=true && ./Allwmake -j && rm -rf build"
        docker export build_latest > build_latest.tar
        docker rm -f $(docker ps -a -q)
        docker rmi -f dafoam/openfoam:2506
        docker import build_latest.tar dafoam/openfoam:2506
        docker push dafoam/openfoam:2506
