name: test_adr

on: [push, pull_request]

env:
  DOCKER_WORKING_DIR: '/home/dockeruser/OpenFOAM-AD'
  DOCKER_MOUNT_DIR: '/home/dockeruser/mount/OpenFOAM-AD'

jobs:

  test_adr:
    runs-on: ubuntu-24.04
    name: Tests
    steps:
    - uses: actions/checkout@v3
    - name: Create the docker container and run the tests
      run: |
        docker pull dafoam/opt-packages:v5
        docker run -i -d -u dockeruser --name of_test -v $GITHUB_WORKSPACE:${{env.DOCKER_MOUNT_DIR}} dafoam/opt-packages:v5 /bin/bash
        docker exec -i of_test /bin/bash -c "cp -r ${{env.DOCKER_MOUNT_DIR}} ${{env.DOCKER_WORKING_DIR}}"
        docker exec -i of_test /bin/bash -c "cd ${{env.DOCKER_WORKING_DIR}} && sed -i 's/export WM_AD_MODE=.*/export WM_AD_MODE=ADR/' etc/bashrc && . etc/bashrc && export WM_QUIET=true && ./Allwmake -j && ./renameAD.sh platforms/linux64GccDPInt32OptADR --commit --ADR "
        docker exec -i of_test /bin/bash -c ". ${{env.DOCKER_WORKING_DIR}}/etc/bashrc && cd ${{env.DOCKER_WORKING_DIR}}/tests && ./Allrun.sh"
